2023-02-11 22:56:07,462 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Configure stats pid to 1514
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/.config/wandb/settings
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/settings
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'masking.ipynb', 'program': '/Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/masking.ipynb'}
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:_log_setup():478] Logging user logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225607-f1dgmntq/logs/debug.log
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225607-f1dgmntq/logs/debug-internal.log
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():518] calling init triggers
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():571] starting backend
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():575] setting up manager
2023-02-11 22:56:07,473 INFO    MainThread:1514 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-11 22:56:07,474 INFO    MainThread:1514 [wandb_init.py:init():582] backend started and connected
2023-02-11 22:56:07,479 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-11 22:56:07,480 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 22:56:07,480 INFO    MainThread:1514 [wandb_init.py:init():670] updated telemetry
2023-02-11 22:56:07,617 INFO    MainThread:1514 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-11 22:56:53,463 WARNING MainThread:1514 [wandb_init.py:init():1129] interrupted
Traceback (most recent call last):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-02-11 22:57:46,885 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Configure stats pid to 1514
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/.config/wandb/settings
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/settings
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'masking.ipynb', 'program': '/Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/masking.ipynb'}
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_init.py:_log_setup():478] Logging user logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225746-v7eups46/logs/debug.log
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225746-v7eups46/logs/debug-internal.log
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():518] calling init triggers
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():571] starting backend
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():575] setting up manager
2023-02-11 22:57:46,895 INFO    MainThread:1514 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-11 22:57:46,896 INFO    MainThread:1514 [wandb_init.py:init():582] backend started and connected
2023-02-11 22:57:46,902 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-11 22:57:46,902 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 22:57:46,902 INFO    MainThread:1514 [wandb_init.py:init():670] updated telemetry
2023-02-11 22:57:46,954 INFO    MainThread:1514 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-11 22:58:47,202 ERROR   MainThread:1514 [wandb_init.py:init():724] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-11 22:58:47,231 ERROR   MainThread:1514 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
